/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.SpecificBadConsequence;
import NapakalakiGame.TreasureKind;

/**
 *
 * @author Antonio
 */
public class SpecificPendingBadConsequenceView extends javax.swing.JPanel {

    private SpecificBadConsequence specificBadConsequenceModel;    
    /**
     * Creates new form SpecificPendingBadConsequenceView
     */
    public SpecificPendingBadConsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence(SpecificBadConsequence bc){
        
        specificBadConsequenceModel = bc;
        specificBadConsequenceView.setBadConsequence(specificBadConsequenceModel);
        repaint();
        revalidate();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        specificBadConsequenceView = new GUI.SpecificBadConsequenceView();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(specificBadConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(specificBadConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.SpecificBadConsequenceView specificBadConsequenceView;
    // End of variables declaration//GEN-END:variables
}
